# Generated by Django 4.0.3 on 2022-06-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
